{% set name = "omnipkg" %}
{% set version = "1.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: # This will need to be updated with the actual SHA256 for version 1.3.9

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"
  entry_points:
    - omnipkg = omnipkg.cli:main
    - 8pkg = omnipkg.cli:main

requirements:
  host:
    - pip
    - python >=3.9,<3.14
    - setuptools >=61.0
  run:
    - python >=3.9,<3.14
    - redis-py >=5.0
    - packaging >=23.0
    - requests >=2.20
    - filelock >=3.9
    - tomli  # [py<311]
    - tqdm
    - python-magic  # [not win]
    - libmagic  # [not win]
    - safety >=2.3.5,<3.0  # [py<310]
    - safety >=3.0  # [py>=310]
    - aiohttp
    - uv

test:
  imports:
    - omnipkg
  commands:
    - omnipkg --help
    - 8pkg --help

about:
  home: https://github.com/1minds3t/omnipkg
  license: AGPL-3.0-only
  license_family: AGPL
  license_file: LICENSE
  summary: 'The Ultimate Python Dependency Resolver. One environment. Infinite packages. Zero conflicts.'
  description: |
    omnipkg simplifies Python dependency management by enabling mid-script version switching and conflict isolation.
    Requires a running Redis server (v5.0+), which must be installed and started separately by the user.
    Tested on Windows, macOS, Linux, and Raspberry Pi.
  doc_url: https://github.com/1minds3t/omnipkg
  dev_url: https://github.com/1minds3t/omnipkg

extra:
  recipe-maintainers:
    - 1minds3t
