{% set name = "omnipkg" %}
{% set version = "1.0.17" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 29dd153d522a02c28d50afa7346547f8cbc01aa709b426b082a003710566af04

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  entry_points:
    - omnipkg = omnipkg.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - redis-py >=4.0.0
    - requests >=2.32.5
    - filelock >=3.19.1
    - packaging >=25.0
    - tqdm >=4.67.1
    - tomli >=2.2.1
    - aiohttp >=3.12.0
    - aiohappyeyeballs >=2.5.0
    - aiosignal >=1.4.0
    - attrs >=17.3.0
    - frozenlist >=1.1.1
    - multidict >=4.5,<7.0
    - propcache >=0.2.0
    - yarl >=1.17.0,<2.0
    - python-magic >=0.4.27  # [not win]
    - libmagic  # [not win]

test:
  imports:
    - omnipkg
  commands:
    - omnipkg --help
    - python -c "import omnipkg; assert omnipkg.__version__ == '1.0.17'"

about:
  home: https://github.com/1minds3t/omnipkg
  license: AGPL-3.0-only
  license_family: AGPL
  license_file: LICENSE
  summary: 'The Ultimate Python Dependency Resolver'
  description: |
    omnipkg simplifies Python dependency management by enabling mid-script version switching and conflict isolation.
    Requires a running Redis server (v4.0.0+), which must be installed and started separately by the user.
    Tested on Windows, macOS, Linux, and Raspberry Pi.

extra:
  recipe-maintainers:
    - 1minds3t