# DO NOT EDIT — generated by dev_tools/gen_help.py from src/omnipkg/help.toml
# source hash: af9d47a97c8d7a49  version: 3.4.0
"""Help text for omnipkg/8pkg, generated from help.toml at build time.

Import this module to get the pre-rendered help string without running
argparse or any other runtime parsing:

    from omnipkg._help import HELP_TEXT, VERSION
    print(HELP_TEXT)
"""

VERSION: str = "3.4.0"

HELP_TEXT: str = """\
usage: 8pkg [-h] [-v] [--lang CODE] [--py VER] [-V] [-y] [-n] <command> ...

🚀 The Python runtime hypervisor that eliminated dependency hell! (8pkg = ∞pkg) 

positional arguments:
  <command>
    install             Install packages with intelligent conflict resolution
    uninstall           Intelligently remove packages and their dependencies
    info                Interactive package/python explorer with version management
    revert              Revert to last known good environment snapshot
    swap                Swap Python version or active package environment
    list                View all installed packages and their status
    python              Manage Python interpreters
    env                 Show recognized environment variables and their current values
    status              Environment health dashboard
    demo                Interactive demo for version switching
    stress-test         Run chaos theory / loader stress tests
    reset               Reset omnipkg subsystems (use 'reset -h' for subcommands)
    config              View or edit omnipkg configuration
    doctor              Diagnose and repair a corrupted environment
    heal                Audit for dependency conflicts and attempt to repair them
    run                 Run a script, CLI command, or inline Python with auto-healing
    daemon              Manage the persistent worker daemon
    web                 Manage the local web bridge
    prune               Clean up old, bubbled package versions
    export              Snapshot current environment to a reproducible lock file
    sync                Rebuild environment from lock file (DESTRUCTIVE)
    upgrade             Upgrade omnipkg or other packages to the latest version

options:
  -v, --version             show program's version number and exit
      --lang CODE           Override the display language for this command (e.g., es, de, ja)
      --py VER              Run under Python VER — or use the alias: 8pkg311, 8pkg312, ...
  -V, --verbose             Enable verbose output for detailed debugging
  -y, --yes                 Skip all confirmation prompts (non-interactive mode)
  -n, --non-interactive     Force non-interactive mode (same as -y; useful in CI/scripts)

Automation/CI: set OMNIPKG_NONINTERACTIVE=1 to disable prompts across all omnipkg processes

Common commands:
  install <pkg>              install, uninstall, info, list, upgrade
  python adopt|switch|info   manage Python interpreters
  reset kb|config            reset knowledge base or configuration
  daemon start|stop|status   manage background worker
  run <script|cmd>           auto-healing script runner

Version: 3.4.0
"""

SUBCOMMAND_HELP: dict[str, str] = {
    'config': """\
usage: 8pkg config [-h]

With no subcommand, prints current config and opens interactive editor.

Examples:
  8pkg config                             # view + interactive edit
  8pkg config set install_strategy latest-active
  8pkg config set language es
  8pkg config view                        # print only, no editor

install_strategy options:
  stable-main    Prefer stable, well-tested releases (default)
  latest-active  Use the very latest version even if pre-release

language options (use 2-letter code):
  en  English     es  Spanish     de  German      fr  French
  ja  Japanese    zh  Chinese     pt  Portuguese  ko  Korean
  ru  Russian     ar  Arabic     (run '8pkg config' for full list)

""",
    'daemon': """\
usage: 8pkg daemon [-h]

Subcommands:
  start    Start the daemon
  stop     Stop the daemon
  restart  Restart the daemon
  status   Show daemon status
  logs     Stream daemon logs
  monitor  Live activity monitor (interactive)

""",
    'demo': """\
usage: 8pkg demo [-h]

Demos (1-10):
  1  Rich test (Python module switching)
  2  UV test (binary switching)
  3  NumPy + SciPy (C-extension switching) — requires Python 3.11
  4  TensorFlow (complex dependency switching) — requires Python 3.11
  5  Multiverse Healing (cross-Python hot-swapping) — requires Python 3.11
  6  Old Flask Test (legacy package healing) — requires Python 3.8
  7  Script-healing Test (omnipkg run scripts)
  8  Quantum Multiverse Warp (concurrent installs) — requires Python 3.11
  9  Flask Port Finder (auto-healing with Flask)
 10  CLI Healing Test (omnipkg run shell commands)

For chaos/stress tests use: 8pkg stress-test

""",
    'doctor': """\
usage: 8pkg doctor [-h] [--dry-run] [--rebuild] [-y]

options:
      --dry-run             preview changes without making them
      --rebuild             nuclear option: wipe broken bubbles and do a full reinstall
  -y, --yes                 skip confirmation prompts

🩺  Finds and removes orphaned package metadata ('ghosts') left behind
   by failed or interrupted installations from other package managers.

Use --dry-run first to see what would be changed, then run without it.

""",
    'env': """\
usage: 8pkg env [-h]

""",
    'export': """\
usage: 8pkg export [-h]

Writes to <venv_root>/.omnipkg/omnipkg.lock by default.
Use --output to override, e.g. for sharing or CI artifacts.

Examples:
  8pkg export                        # write to default location
  8pkg export -o /tmp/my.lock        # explicit path
  8pkg export --python 3.11          # only capture python 3.11

""",
    'heal': """\
usage: 8pkg heal [-h]

❤️‍🩹  Automatically resolves version conflicts and installs missing packages
   required by your currently installed packages.

Tip: run with --dry-run first to preview changes.

""",
    'info': """\
usage: 8pkg info [-h]

Examples:
  8pkg info requests
  8pkg info requests 1        # Automatically select the first installation
  8pkg info requests 1 -y     # Select first and auto-expand raw data
  8pkg info python            # Show managed Python interpreters

""",
    'install': """\
usage: 8pkg install [-h] [-U] [--requirement FILE] [--force] [-y] [--dry-run] [--strategy STRATEGY] [--target DIR] [--no-deps] [--pre] [--no-cache-dir] [--index-url URL] [--extra-index-url URL] [--find-links URL] [--trusted-host HOST] [--timeout SECS] [--retries N] [--no-binary PKG] [--only-binary PKG] [--ignore-installed]

options:
  -U, --upgrade             upgrade package to latest version
  -r, --requirement FILE    install from requirements file
      --force               force reinstall even if already satisfied (alias: --force-reinstall)
  -y, --yes                 skip all confirmation prompts
      --dry-run             resolve and validate packages without installing anything
      --strategy STRATEGY   override install strategy for this run: stable-main | latest-active
  -t, --target DIR          install packages into DIR instead of the active environment
      --no-deps             don't install package dependencies
      --pre                 include pre-release and development versions
      --no-cache-dir        disable the pip/uv cache for this install
  -i, --index-url URL       base URL of the package index (overrides PyPI)
      --extra-index-url URL additional package index URL (searched after --index-url)
  -f, --find-links URL      search this directory or URL for wheels before hitting the index
      --trusted-host HOST   mark HOST as trusted even without HTTPS
      --timeout SECS        socket timeout for network requests (default: 15)
      --retries N           number of retries on network failure (default: 5)
      --no-binary PKG       don't use binary packages for PKG (use :all: for everything)
      --only-binary PKG     only use binary packages for PKG (use :all: for everything)
      --ignore-installed    ignore already-installed packages and reinstall

Examples:
  8pkg install requests
  8pkg install 'numpy>=1.20' scipy
  8pkg install uv==0.7.13 uv==0.7.14        # coexisting versions!
  8pkg install python==3.11                  # adopt a Python interpreter
  8pkg install -r requirements.txt
  8pkg install --force requests              # force reinstall
  8pkg install --dry-run requests            # preview only, no changes
  8pkg install --strategy latest-active requests  # override install strategy
  8pkg install --target /tmp/pkgs requests   # install to custom directory
  8pkg install --no-deps requests            # skip dependency resolution
  8pkg install --pre requests                # include pre-release versions
  8pkg install --find-links /path requests   # search local directory for wheels
  8pkg install --no-binary :all: requests    # force source builds
  8pkg install --only-binary :all: requests  # force binary wheels only
  8pkg -y install requests                   # skip all prompts
  8pkg311 install requests                   # install under Python 3.11

""",
    'list': """\
usage: 8pkg list [-h]

""",
    'prune': """\
usage: 8pkg prune [-h]

""",
    'python': """\
usage: 8pkg python [-h]

Subcommands:
  adopt 3.11          Copy or download Python 3.11 into the managed pool
  adopt 3.9 --force   Re-adopt even if already managed (overwrites)
  switch 3.11         Switch active Python (same as 'swap python 3.11')
  reinstall 3.9       Remove + re-adopt Python 3.9 (clean reinstall)
  remove 3.8          Remove a managed interpreter
  rescan              Re-scan and repair the interpreter registry

""",
    'reset': """\
usage: 8pkg reset [-h]

Subcommands:
  kb      Rebuild the omnipkg knowledge base (default)
  config  Delete config file for a fresh setup

Examples:
  8pkg reset kb
  8pkg reset config -y

""",
    'revert': """\
usage: 8pkg revert [-h]

Reverts to the most recent automatic snapshot taken before an install or uninstall.
Use --list to see available snapshots.

""",
    'run': """\
usage: 8pkg run [-h]

USAGE:
  8pkg run <script.py> [args...]    run a Python script
  8pkg run <cli-tool> [args...]     run any installed CLI tool
  8pkg run python -c "code"        run inline Python
  8pkg run python -                run Python from stdin
  8pkg run python -m module        run a module

EXAMPLES:
  8pkg run my_script.py --arg 1
  8pkg run pytest tests/ -x
  8pkg run uvicorn main:app --reload
  8pkg run python -c "import pandas; print(pandas.__version__)"
  echo "import requests" | 8pkg run python -
  8pkg38 run pytest                # run under Python 3.8
  8pkg --py 3.8 run pytest         # same via flag

NOTE: 'python' here means the system/configured python, not a literal
8pkg subcommand. If it conflicts, use the full path or 8pkg38/8pkg311 aliases.

""",
    'status': """\
usage: 8pkg status [-h]

""",
    'stress-test': """\
usage: 8pkg stress-test [-h]

⚠️  Each test exercises extreme ABI switching scenarios.
   Tests are designed to run individually — running all at once is unsafe.
   Default (no args): launches interactive menu; picks test 1 in non-interactive mode.

Example:
  8pkg stress-test        # interactive menu
  8pkg stress-test 3      # run test 3 only
  8pkg -y stress-test 3   # run test 3, no prompt

""",
    'swap': """\
usage: 8pkg swap [-h]

Swapping Python versions:
  8pkg swap python 3.11    # Spawns a new shell running Python 3.11
                            # In CI (non-interactive): updates config only
  8pkg swap python         # Interactive picker if no version given

Swapping package versions:
  8pkg swap numpy==1.26.4  # Switch numpy to a specific version

Alias: 'python switch <ver>' does the same thing as 'swap python <ver>'

""",
    'sync': """\
usage: 8pkg sync [-h]

Reads from <venv_root>/.omnipkg/omnipkg.lock by default.
Clears and reinstalls all packages for each python in the lock file.

Examples:
  8pkg sync                          # sync from default lock file
  8pkg sync /path/to/other.lock      # explicit lock file
  8pkg sync --python 3.11            # only sync python 3.11
  8pkg sync --yes                    # skip confirmation (CI/Docker)

""",
    'uninstall': """\
usage: 8pkg uninstall [-h]

""",
    'upgrade': """\
usage: 8pkg upgrade [-h]

""",
    'web': """\
usage: 8pkg web [-h]

The web bridge connects the omnipkg dashboard UI to your local machine.

Commands:
  start           Start the bridge (opens browser, shows permission prompt)
  stop            Stop the bridge
  restart         Stop then start
  status          Show PID, port, memory, uptime
  logs            Tail the bridge log file
  fix-permission  Chrome blocked 'local network access'? Run this.

""",
}
