/* DO NOT EDIT — generated by dev_tools/gen_help.py from src/omnipkg/help.toml */
/* source hash: af9d47a97c8d7a49  version: 3.4.1 */
#ifndef OMNIPKG_HELP_H
#define OMNIPKG_HELP_H

/* OMNIPKG_HELP_TEXT — full --help output, embedded at compile time.
 * Use:  if (want_help) { fputs(OMNIPKG_HELP_TEXT, stdout); return 0; }
 * Zero runtime IO, zero parsing, zero Python startup. */
static const char OMNIPKG_HELP_TEXT[] =
    "usage: 8pkg [-h] [-v] [--lang CODE] [--py VER] [-V] [-y] [-n] <command> ...\n"
    "\n"
    "🚀 The Python runtime hypervisor that eliminated dependency hell! (8pkg = ∞pkg) \n"
    "\n"
    "positional arguments:\n"
    "  <command>\n"
    "    install             Install packages with intelligent conflict resolution\n"
    "    uninstall           Intelligently remove packages and their dependencies\n"
    "    info                Interactive package/python explorer with version management\n"
    "    revert              Revert to last known good environment snapshot\n"
    "    swap                Swap Python version or active package environment\n"
    "    list                View all installed packages and their status\n"
    "    python              Manage Python interpreters\n"
    "    env                 Show recognized environment variables and their current values\n"
    "    status              Environment health dashboard\n"
    "    demo                Interactive demo for version switching\n"
    "    stress-test         Run chaos theory / loader stress tests\n"
    "    reset               Reset omnipkg subsystems (use 'reset -h' for subcommands)\n"
    "    config              View or edit omnipkg configuration\n"
    "    doctor              Diagnose and repair a corrupted environment\n"
    "    heal                Audit for dependency conflicts and attempt to repair them\n"
    "    run                 Run a script, CLI command, or inline Python with auto-healing\n"
    "    daemon              Manage the persistent worker daemon\n"
    "    web                 Manage the local web bridge\n"
    "    prune               Clean up old, bubbled package versions\n"
    "    export              Snapshot current environment to a reproducible lock file\n"
    "    sync                Rebuild environment from lock file (DESTRUCTIVE)\n"
    "    upgrade             Upgrade omnipkg or other packages to the latest version\n"
    "\n"
    "options:\n"
    "  -v, --version             show program's version number and exit\n"
    "      --lang CODE           Override the display language for this command (e.g., es, de, ja)\n"
    "      --py VER              Run under Python VER — or use the alias: 8pkg311, 8pkg312, ...\n"
    "  -V, --verbose             Enable verbose output for detailed debugging\n"
    "  -y, --yes                 Skip all confirmation prompts (non-interactive mode)\n"
    "  -n, --non-interactive     Force non-interactive mode (same as -y; useful in CI/scripts)\n"
    "\n"
    "Automation/CI: set OMNIPKG_NONINTERACTIVE=1 to disable prompts across all omnipkg processes\n"
    "\n"
    "Common commands:\n"
    "  install <pkg>              install, uninstall, info, list, upgrade\n"
    "  python adopt|switch|info   manage Python interpreters\n"
    "  reset kb|config            reset knowledge base or configuration\n"
    "  daemon start|stop|status   manage background worker\n"
    "  run <script|cmd>           auto-healing script runner\n"
    "\n"
    "Version: 3.4.1\n"
    "";

static const char OMNIPKG_HELP_CONFIG[] =
    "usage: 8pkg config [-h]\n"
    "\n"
    "With no subcommand, prints current config and opens interactive editor.\n"
    "\n"
    "Examples:\n"
    "  8pkg config                             # view + interactive edit\n"
    "  8pkg config set install_strategy latest-active\n"
    "  8pkg config set language es\n"
    "  8pkg config view                        # print only, no editor\n"
    "\n"
    "install_strategy options:\n"
    "  stable-main    Prefer stable, well-tested releases (default)\n"
    "  latest-active  Use the very latest version even if pre-release\n"
    "\n"
    "language options (use 2-letter code):\n"
    "  en  English     es  Spanish     de  German      fr  French\n"
    "  ja  Japanese    zh  Chinese     pt  Portuguese  ko  Korean\n"
    "  ru  Russian     ar  Arabic     (run '8pkg config' for full list)\n"
    "\n"
    "";

static const char OMNIPKG_HELP_DAEMON[] =
    "usage: 8pkg daemon [-h]\n"
    "\n"
    "Subcommands:\n"
    "  start    Start the daemon\n"
    "  stop     Stop the daemon\n"
    "  restart  Restart the daemon\n"
    "  status   Show daemon status\n"
    "  logs     Stream daemon logs\n"
    "  monitor  Live activity monitor (interactive)\n"
    "\n"
    "";

static const char OMNIPKG_HELP_DEMO[] =
    "usage: 8pkg demo [-h]\n"
    "\n"
    "Demos (1-10):\n"
    "  1  Rich test (Python module switching)\n"
    "  2  UV test (binary switching)\n"
    "  3  NumPy + SciPy (C-extension switching) — requires Python 3.11\n"
    "  4  TensorFlow (complex dependency switching) — requires Python 3.11\n"
    "  5  Multiverse Healing (cross-Python hot-swapping) — requires Python 3.11\n"
    "  6  Old Flask Test (legacy package healing) — requires Python 3.8\n"
    "  7  Script-healing Test (omnipkg run scripts)\n"
    "  8  Quantum Multiverse Warp (concurrent installs) — requires Python 3.11\n"
    "  9  Flask Port Finder (auto-healing with Flask)\n"
    " 10  CLI Healing Test (omnipkg run shell commands)\n"
    "\n"
    "For chaos/stress tests use: 8pkg stress-test\n"
    "\n"
    "";

static const char OMNIPKG_HELP_DOCTOR[] =
    "usage: 8pkg doctor [-h] [--dry-run] [--rebuild] [-y]\n"
    "\n"
    "options:\n"
    "      --dry-run             preview changes without making them\n"
    "      --rebuild             nuclear option: wipe broken bubbles and do a full reinstall\n"
    "  -y, --yes                 skip confirmation prompts\n"
    "\n"
    "🩺  Finds and removes orphaned package metadata ('ghosts') left behind\n"
    "   by failed or interrupted installations from other package managers.\n"
    "\n"
    "Use --dry-run first to see what would be changed, then run without it.\n"
    "\n"
    "";

static const char OMNIPKG_HELP_ENV[] =
    "usage: 8pkg env [-h]\n"
    "\n"
    "";

static const char OMNIPKG_HELP_EXPORT[] =
    "usage: 8pkg export [-h]\n"
    "\n"
    "Writes to <venv_root>/.omnipkg/omnipkg.lock by default.\n"
    "Use --output to override, e.g. for sharing or CI artifacts.\n"
    "\n"
    "Examples:\n"
    "  8pkg export                        # write to default location\n"
    "  8pkg export -o /tmp/my.lock        # explicit path\n"
    "  8pkg export --python 3.11          # only capture python 3.11\n"
    "\n"
    "";

static const char OMNIPKG_HELP_HEAL[] =
    "usage: 8pkg heal [-h]\n"
    "\n"
    "❤️‍🩹  Automatically resolves version conflicts and installs missing packages\n"
    "   required by your currently installed packages.\n"
    "\n"
    "Tip: run with --dry-run first to preview changes.\n"
    "\n"
    "";

static const char OMNIPKG_HELP_INFO[] =
    "usage: 8pkg info [-h]\n"
    "\n"
    "Examples:\n"
    "  8pkg info requests\n"
    "  8pkg info requests 1        # Automatically select the first installation\n"
    "  8pkg info requests 1 -y     # Select first and auto-expand raw data\n"
    "  8pkg info python            # Show managed Python interpreters\n"
    "\n"
    "";

static const char OMNIPKG_HELP_INSTALL[] =
    "usage: 8pkg install [-h] [-U] [--requirement FILE] [--force] [-y] [--dry-run] [--strategy STRATEGY] [--target DIR] [--no-deps] [--pre] [--no-cache-dir] [--index-url URL] [--extra-index-url URL] [--find-links URL] [--trusted-host HOST] [--timeout SECS] [--retries N] [--no-binary PKG] [--only-binary PKG] [--ignore-installed]\n"
    "\n"
    "options:\n"
    "  -U, --upgrade             upgrade package to latest version\n"
    "  -r, --requirement FILE    install from requirements file\n"
    "      --force               force reinstall even if already satisfied (alias: --force-reinstall)\n"
    "  -y, --yes                 skip all confirmation prompts\n"
    "      --dry-run             resolve and validate packages without installing anything\n"
    "      --strategy STRATEGY   override install strategy for this run: stable-main | latest-active\n"
    "  -t, --target DIR          install packages into DIR instead of the active environment\n"
    "      --no-deps             don't install package dependencies\n"
    "      --pre                 include pre-release and development versions\n"
    "      --no-cache-dir        disable the pip/uv cache for this install\n"
    "  -i, --index-url URL       base URL of the package index (overrides PyPI)\n"
    "      --extra-index-url URL additional package index URL (searched after --index-url)\n"
    "  -f, --find-links URL      search this directory or URL for wheels before hitting the index\n"
    "      --trusted-host HOST   mark HOST as trusted even without HTTPS\n"
    "      --timeout SECS        socket timeout for network requests (default: 15)\n"
    "      --retries N           number of retries on network failure (default: 5)\n"
    "      --no-binary PKG       don't use binary packages for PKG (use :all: for everything)\n"
    "      --only-binary PKG     only use binary packages for PKG (use :all: for everything)\n"
    "      --ignore-installed    ignore already-installed packages and reinstall\n"
    "\n"
    "Examples:\n"
    "  8pkg install requests\n"
    "  8pkg install 'numpy>=1.20' scipy\n"
    "  8pkg install uv==0.7.13 uv==0.7.14        # coexisting versions!\n"
    "  8pkg install python==3.11                  # adopt a Python interpreter\n"
    "  8pkg install -r requirements.txt\n"
    "  8pkg install --force requests              # force reinstall\n"
    "  8pkg install --dry-run requests            # preview only, no changes\n"
    "  8pkg install --strategy latest-active requests  # override install strategy\n"
    "  8pkg install --target /tmp/pkgs requests   # install to custom directory\n"
    "  8pkg install --no-deps requests            # skip dependency resolution\n"
    "  8pkg install --pre requests                # include pre-release versions\n"
    "  8pkg install --find-links /path requests   # search local directory for wheels\n"
    "  8pkg install --no-binary :all: requests    # force source builds\n"
    "  8pkg install --only-binary :all: requests  # force binary wheels only\n"
    "  8pkg -y install requests                   # skip all prompts\n"
    "  8pkg311 install requests                   # install under Python 3.11\n"
    "\n"
    "";

static const char OMNIPKG_HELP_LIST[] =
    "usage: 8pkg list [-h]\n"
    "\n"
    "";

static const char OMNIPKG_HELP_PRUNE[] =
    "usage: 8pkg prune [-h]\n"
    "\n"
    "";

static const char OMNIPKG_HELP_PYTHON[] =
    "usage: 8pkg python [-h]\n"
    "\n"
    "Subcommands:\n"
    "  adopt 3.11          Copy or download Python 3.11 into the managed pool\n"
    "  adopt 3.9 --force   Re-adopt even if already managed (overwrites)\n"
    "  switch 3.11         Switch active Python (same as 'swap python 3.11')\n"
    "  reinstall 3.9       Remove + re-adopt Python 3.9 (clean reinstall)\n"
    "  remove 3.8          Remove a managed interpreter\n"
    "  rescan              Re-scan and repair the interpreter registry\n"
    "\n"
    "";

static const char OMNIPKG_HELP_RESET[] =
    "usage: 8pkg reset [-h]\n"
    "\n"
    "Subcommands:\n"
    "  kb      Rebuild the omnipkg knowledge base (default)\n"
    "  config  Delete config file for a fresh setup\n"
    "\n"
    "Examples:\n"
    "  8pkg reset kb\n"
    "  8pkg reset config -y\n"
    "\n"
    "";

static const char OMNIPKG_HELP_REVERT[] =
    "usage: 8pkg revert [-h]\n"
    "\n"
    "Reverts to the most recent automatic snapshot taken before an install or uninstall.\n"
    "Use --list to see available snapshots.\n"
    "\n"
    "";

static const char OMNIPKG_HELP_RUN[] =
    "usage: 8pkg run [-h]\n"
    "\n"
    "USAGE:\n"
    "  8pkg run <script.py> [args...]    run a Python script\n"
    "  8pkg run <cli-tool> [args...]     run any installed CLI tool\n"
    "  8pkg run python -c \"code\"        run inline Python\n"
    "  8pkg run python -                run Python from stdin\n"
    "  8pkg run python -m module        run a module\n"
    "\n"
    "EXAMPLES:\n"
    "  8pkg run my_script.py --arg 1\n"
    "  8pkg run pytest tests/ -x\n"
    "  8pkg run uvicorn main:app --reload\n"
    "  8pkg run python -c \"import pandas; print(pandas.__version__)\"\n"
    "  echo \"import requests\" | 8pkg run python -\n"
    "  8pkg38 run pytest                # run under Python 3.8\n"
    "  8pkg --py 3.8 run pytest         # same via flag\n"
    "\n"
    "NOTE: 'python' here means the system/configured python, not a literal\n"
    "8pkg subcommand. If it conflicts, use the full path or 8pkg38/8pkg311 aliases.\n"
    "\n"
    "";

static const char OMNIPKG_HELP_STATUS[] =
    "usage: 8pkg status [-h]\n"
    "\n"
    "";

static const char OMNIPKG_HELP_STRESS_TEST[] =
    "usage: 8pkg stress-test [-h]\n"
    "\n"
    "⚠️  Each test exercises extreme ABI switching scenarios.\n"
    "   Tests are designed to run individually — running all at once is unsafe.\n"
    "   Default (no args): launches interactive menu; picks test 1 in non-interactive mode.\n"
    "\n"
    "Example:\n"
    "  8pkg stress-test        # interactive menu\n"
    "  8pkg stress-test 3      # run test 3 only\n"
    "  8pkg -y stress-test 3   # run test 3, no prompt\n"
    "\n"
    "";

static const char OMNIPKG_HELP_SWAP[] =
    "usage: 8pkg swap [-h]\n"
    "\n"
    "Swapping Python versions:\n"
    "  8pkg swap python 3.11    # Spawns a new shell running Python 3.11\n"
    "                            # In CI (non-interactive): updates config only\n"
    "  8pkg swap python         # Interactive picker if no version given\n"
    "\n"
    "Swapping package versions:\n"
    "  8pkg swap numpy==1.26.4  # Switch numpy to a specific version\n"
    "\n"
    "Alias: 'python switch <ver>' does the same thing as 'swap python <ver>'\n"
    "\n"
    "";

static const char OMNIPKG_HELP_SYNC[] =
    "usage: 8pkg sync [-h]\n"
    "\n"
    "Reads from <venv_root>/.omnipkg/omnipkg.lock by default.\n"
    "Clears and reinstalls all packages for each python in the lock file.\n"
    "\n"
    "Examples:\n"
    "  8pkg sync                          # sync from default lock file\n"
    "  8pkg sync /path/to/other.lock      # explicit lock file\n"
    "  8pkg sync --python 3.11            # only sync python 3.11\n"
    "  8pkg sync --yes                    # skip confirmation (CI/Docker)\n"
    "\n"
    "";

static const char OMNIPKG_HELP_UNINSTALL[] =
    "usage: 8pkg uninstall [-h]\n"
    "\n"
    "";

static const char OMNIPKG_HELP_UPGRADE[] =
    "usage: 8pkg upgrade [-h]\n"
    "\n"
    "";

static const char OMNIPKG_HELP_WEB[] =
    "usage: 8pkg web [-h]\n"
    "\n"
    "The web bridge connects the omnipkg dashboard UI to your local machine.\n"
    "\n"
    "Commands:\n"
    "  start           Start the bridge (opens browser, shows permission prompt)\n"
    "  stop            Stop the bridge\n"
    "  restart         Stop then start\n"
    "  status          Show PID, port, memory, uptime\n"
    "  logs            Tail the bridge log file\n"
    "  fix-permission  Chrome blocked 'local network access'? Run this.\n"
    "\n"
    "";

#define OMNIPKG_VERSION "3.4.1"

#endif /* OMNIPKG_HELP_H */
