name: Codacy Security & Style Scan
on: push: branches: [ "main" ] pull_request: branches: [ "main" ] schedule: - cron: '17 7 * * 2'
permissions: contents: read
jobs: codacy-scan: permissions: contents: read security-events: write actions: read name: Codacy Scan runs-on: ubuntu-latest steps: - name: Checkout code uses: actions/checkout@v4
  # --- STEP 1: Run Bandit Security Analysis ---
 - name: Run Codacy Security Analysis
   uses: codacy/codacy-analysis-cli-action@v4
   with:
     tool: bandit
     project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
     verbose: true
     # The output is now explicitly placed in a known directory
     output: results-security.sarif
     format: sarif
     gh-code-scanning-compat: true
     max-allowed-issues: 2147483647

 # --- STEP 2: Run Pylint Code Style Analysis ---
 - name: Run Codacy Code Style Analysis
   uses: codacy/codacy-analysis-cli-action@v4
   with:
     tool: pylint
     project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
     verbose: true
     # The output for this analysis is placed in its own file
     output: results-style.sarif
     format: sarif
     gh-code-scanning-compat: true
     max-allowed-issues: 2147483647
     
 # --- STEP 3: Upload the separate SARIF files ---
 - name: Upload SARIF results to GitHub
   uses: github/codeql-action/upload-sarif@v3
   with:
     # The uploader is configured to explicitly find both files.
     # The previous error was a failure of the Codacy action itself
     # to properly persist the file. This YAML is the correct syntax
     # to tell the uploader where to look.
     sarif_file: |
       results-security.sarif
       results-style.sarif
