# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: EthicalCheck-Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '26 2 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Trigger_EthicalCheck:
    permissions:
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      # CORRECTED: The action has been updated to the new official version.
      - name: APIsec Scan
        uses: apisec-inc/apisec-run-scan@v1.0.6
        with:
          # NOTE: The parameters have changed for this new action.
          # You will need to create an account at apisec.ai and create a project.
          # Then, store these values as secrets in your repository settings.
          
          # 1. Create a secret named APISEC_USERNAME with your APIsec username.
          apisec-username: ${{ secrets.APISEC_USERNAME }}
          
          # 2. Create a secret named APISEC_PASSWORD with your APIsec password.
          apisec-password: ${{ secrets.APISEC_PASSWORD }}
          
          # 3. Create a secret named APISEC_PROJECT with the name of your project in the APIsec platform.
          apisec-project: ${{ secrets.APISEC_PROJECT }}
          
          # The sarif-result-file parameter is no longer needed; the new action handles this automatically.

      - name: Upload sarif file to repository
        # This step is correctly configured to upload the results file.
        uses: github/codeql-action/upload-sarif@v3
        with:
          # The new action outputs the SARIF file to a default location.
          # This path might need to be adjusted based on the action's output logs if it differs.
          sarif_file: apisec-results.sarif
