name: Build and Publish Ruby Gem

on:
  release:
    types: [published] # This is the trigger for your official public releases
  push:
    branches: [ "main" ] # This can be used for pre-releases or internal builds

jobs:
  build-and-publish:
    name: Build and Publish Gem
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required for pushing to GitHub Packages Registry (GPR)

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby 3.1
      # Use a modern, secure, and supported version of Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true # Caches your dependencies for faster runs

    # --- STEP 1: BUILD THE GEM ONCE ---
    - name: Build the gem
      run: |
        # This creates the .gem file that we will use for all subsequent steps
        gem build *.gemspec
        # List the file to make sure it was created
        ls *.gem

    # --- STEP 2: PUBLISH TO GITHUB PACKAGES (GPR) ---
    # This can run on every push to main for internal testing
    - name: Publish to GitHub Packages
      run: |
        # This step has its own, clean credential setup
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: Bearer ${{secrets.GITHUB_TOKEN}}\n" > $HOME/.gem/credentials
        
        # Push the artifact we built in the previous step
        gem push --KEY github --host https://rubygems.pkg.github.com/${{ github.repository_owner }} *.gem
      
    # --- STEP 3: PUBLISH TO RUBYGEMS.ORG (OFFICIAL RELEASE) ---
    # This step will ONLY run when you create a new release on GitHub
    - name: Publish to RubyGems.org
      if: github.event_name == 'release'
      run: |
        # This step also has its own, clean credential setup
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${{secrets.RUBYGEMS_AUTH_TOKEN}}\n" > $HOME/.gem/credentials
        
        # Push the exact same artifact to the public registry
        gem push *.gem
      env:
        # It's a good practice to name the secret clearly
        RUBYGEMS_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
